import {Link,useParams} from "react-router-dom";import {useState} from "react";import Storefront from "../components/Storefront";import {demoOrders,products} from "../data";import {getOrders,updateOrder,calculateCommission,releaseSettlement} from "../services/mvecStore";
const money=n=>new Intl.NumberFormat("en-RW").format(Number(n)||0)+" RWF";
export default function OrderDetails(){
 const {id}=useParams();const local=getOrders().find(x=>String(x.id)===String(id));const order=local||demoOrders.find(x=>String(x.id)===String(id))||demoOrders[0];
 const item=order.items?.[0],p=products.find(x=>String(x.id)===String(item?.productId))||products.find(x=>x.vendor===order.vendor)||products[0];
 const [reported,setReported]=useState(false),[reason,setReason]=useState(""),[review,setReview]=useState("");
 const statusList=["Created","Payment Confirmed","Preparing","Shipped","Out for Delivery","Delivered","Completed"];
 const idx=Math.max(0,statusList.indexOf(order.status));
 const report=()=>{if(!reason)return;updateOrder(order.id,{disputeStatus:"open",disputeReason:reason});setReported(true)};
 const reviewOrder=()=>{if(review.trim())updateOrder(order.id,{review:review.trim(),reviewStatus:"submitted"});};
 return <Storefront><main className="account-page"><div className="page-title"><span className="eyebrow">ORDER DETAILS</span><h1>{order.id}</h1><p>Payment, fulfillment and trust information for this order.</p></div>
 <div className="detail-grid"><section className="data-card"><div className="data-card-head"><div><h3>Order information</h3><span>{order.date}</span></div><em className="status active">{order.status}</em></div><div className="order-product"><img src={p.image} alt=""/><div><b>{item?.name||p.name}</b><small>{p.sku} · Qty {item?.qty||1}</small><strong>{money(order.total)}</strong></div></div><div className="order-summary-lines"><span>Products <b>{money(order.subtotal||order.total)}</b></span><span>Shipping <b>{money(order.shipping||0)}</b></span><span className="grand">Grand total <b>{money(order.total)}</b></span></div></section>
 <section className="data-card"><h3>Seller & payment</h3><div className="profile-detail"><b>{order.vendor}</b><span>MVEC Verified seller ✓</span><span>Payment: {order.payment||"PENDING"}</span><span>Method: {order.paymentMethod||"Not selected"}</span><span>Settlement: {order.settlementStatus==="RELEASED"?"Released to seller":order.payment==="SUCCESS"?"Funds held by MVEC":"Not funded"}</span></div><h3 className="subhead">MVEC commission</h3><span>{money(order.commission||calculateCommission(order.subtotal||order.total))} recorded as marketplace commission</span></section></div>
 <section className="data-card"><div className="data-card-head"><div><h3>Delivery timeline</h3><span>Delivery proof is recorded at completion.</span></div></div><div className="timeline">{statusList.map((s,i)=><div className={i<=idx?"timeline-item done":"timeline-item"} key={s}><i/><div><b>{s}</b><small>{i===idx?"Current order status":"MVEC workflow step"}</small></div></div>)}</div>{order.status==="Delivered"||order.status==="Completed"?<div className="verified-box"><b>✓ Delivery proof recorded</b><p>Buyer confirmation/approved delivery evidence can be used by MVEC when resolving disputes.</p></div>:null}</section>
 {(order.status==="Delivered"||order.status==="Completed")&&<section className="data-card"><h3>Leave a review</h3><textarea className="field" value={review} onChange={e=>setReview(e.target.value)} placeholder="Tell other buyers about your experience…"/><button className="gradient-btn" onClick={reviewOrder}>Submit review</button></section>}
 <section className="data-card"><h3>Report a problem</h3>{reported?<div className="form-alert success">Your problem was reported. MVEC support can review the order and evidence.</div>:<><select className="field" value={reason} onChange={e=>setReason(e.target.value)}><option value="">Choose a problem</option><option>Product not received</option><option>Wrong product</option><option>Damaged product</option><option>Missing item</option><option>Product differs from description</option><option>Other</option></select><button className="outline-btn" onClick={report}>Report a problem</button></>}</section>
 <Link className="outline-btn" to="/orders">← Back to orders</Link></main></Storefront>
}