import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import MarketplaceLayout from '../components/MarketplaceLayout';
import ProductCard from '../components/ProductCard';
import { categories, products } from '../data';

export default function Shop() {
  const [params] = useSearchParams(); const initial = params.get('q') || ''; const [search,setSearch]=useState(initial); const [category,setCategory]=useState(params.get('category')||''); const [brand,setBrand]=useState(''); const [max,setMax]=useState(1000000); const [sort,setSort]=useState('featured');
  const filtered=useMemo(()=>{let list=products.filter(p=>(!search || `${p.name} ${p.sku} ${p.brand} ${p.vendor} ${p.description} ${Object.values(p.attributes).join(' ')}`.toLowerCase().includes(search.toLowerCase())) && (!category||p.category===category) && (!brand||p.brand===brand) && p.price<=max); if(sort==='price-low') list.sort((a,b)=>a.price-b.price); if(sort==='rating') list.sort((a,b)=>b.rating-a.rating); if(sort==='deals') list.sort((a,b)=>(b.oldPrice-b.price)-(a.oldPrice-a.price)); return list;},[search,category,brand,max,sort]);
  return <MarketplaceLayout search={search} setSearch={setSearch}><div className="shop-page"><aside className="filters"><div className="filter-head"><h3>Filters</h3><button onClick={()=>{setCategory('');setBrand('');setMax(1000000)}}>Clear</button></div><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">All brands</option>{[...new Set(products.map(p=>p.brand))].map(b=><option key={b}>{b}</option>)}</select></label><label>Maximum price<input type="range" min="20000" max="1000000" step="10000" value={max} onChange={e=>setMax(+e.target.value)}/><b>{max.toLocaleString()} RWF</b></label><div className="filter-checks"><span>Availability</span><label><input type="checkbox" defaultChecked/> In stock</label><label><input type="checkbox"/> New arrivals</label><label><input type="checkbox"/> Discounted</label></div></aside><main className="shop-results"><div className="shop-title"><div><small>MVEC MARKETPLACE</small><h1>Shop</h1><p>{filtered.length} products found</p></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="deals">Best deals</option><option value="rating">Top rated</option><option value="price-low">Price: low to high</option></select></div><div className="product-grid">{filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div></main></div></MarketplaceLayout>;
}
