import {useEffect,useMemo,useState} from "react";
import Icon from "./Icon";
import {getOrders,getDeliveryRemaining,syncOrderLifecycle} from "../services/mvecStore";
import Pagination from "./Pagination";
const money=n=>new Intl.NumberFormat("en-RW").format(Number(n)||0)+" RWF";
const steps=["Order placed","Payment confirmed","Preparing","Shipped","In transit","Out for delivery","Delivered"];
const fmt=ms=>{const s=Math.max(0,Math.floor(ms/1000));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};
export default function DeliveryTracking({role="vendor"}){
 const [orders,setOrders]=useState(()=>getOrders().filter(o=>o.payment==="SUCCESS"));const [q,setQ]=useState("");const [page,setPage]=useState(1);const [tick,setTick]=useState(0);const perPage=5;
 useEffect(()=>{const timer=setInterval(()=>{syncOrderLifecycle();setOrders(getOrders().filter(o=>o.payment==="SUCCESS"));setTick(x=>x+1)},1000);return()=>clearInterval(timer)},[]);
 const roleOrders=role==="supplier"?orders.filter(o=>o.supplier||o.id.startsWith("B2B")):role==="vendor"?orders.filter(o=>o.vendor):role==="affiliate"?orders.filter(o=>o.affiliateCode):orders;
 const filtered=useMemo(()=>roleOrders.filter(o=>JSON.stringify(o).toLowerCase().includes(q.toLowerCase())),[roleOrders,q,tick]);const shown=filtered.slice((page-1)*perPage,page*perPage);
 return <><div className="dash-page-head"><div><span className="eyebrow">DELIVERY & SETTLEMENT</span><h1>{role==='admin'?'All deliveries':'Delivery tracking'}</h1><p>Track delivery progress, the protected amount and the final delivery confirmation.</p></div></div>
 <div className="verified-box settlement-banner"><b>🔒 Protected funds</b><p>Paid orders are recorded as <strong>HELD by MVEC</strong> until the buyer's delivery OTP is verified. After successful verification, the protected amount is released according to the settlement rules.</p></div>
 <div className="dash-toolbar"><div className="dash-filter"><Icon name="search"/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search order, product, customer, vendor or tracking number…"/></div></div>
 <div className="data-card"><div className="data-card-head"><div><h3>Delivery operations</h3><span>{filtered.length} paid orders</span></div></div>
 {shown.map(o=>{const current=o.deliveryStatus||o.status||"Order placed";const idx=Math.max(0,steps.findIndex(s=>s.toLowerCase()===String(current).toLowerCase()));const remaining=getDeliveryRemaining(o);return <div className="delivery-track-card" key={o.id}><div className="delivery-track-head"><div><b>{o.id}</b><small>{o.items?.[0]?.name||o.productName||"Order"} · {o.trackingNumber}</small><small>{o.buyer||"Buyer"} · {o.vendor||"Marketplace seller"}</small></div><div className="settlement-chip"><span className={o.settlementStatus==='RELEASED'?'released':'held'}>{o.settlementStatus==='RELEASED'?'Funds released':'Funds held by MVEC'}</span><strong>{money(o.heldAmount||o.total)}</strong></div></div><div className="delivery-steps">{steps.map((s,i)=><div className={i<=idx?'step done':'step'} key={s}><i>{i<idx?'✓':i===idx?'●':''}</i><small>{s}</small></div>)}</div><div className="delivery-track-actions"><span>Payment: <b>{o.payment}</b></span><span>Time left: <b>{o.settlementStatus==='HELD'?fmt(remaining):'Completed'}</b></span><span>OTP: <b>{o.deliveryOtpVerified?'Verified ✓':'Awaiting delivery verification'}</b></span><span>Funds: <b>{o.settlementStatus==='HELD'?'Held by MVEC':'Released'}</b></span></div>{o.settlementStatus==='HELD'&&<p className="tiny delivery-note">The delivery person must obtain the buyer's OTP at the door. The correct OTP confirms delivery for both sides and triggers the settlement release.</p>}{o.refundStatus==='FULL'&&<p className="form-alert error">Order cancelled after the delivery window expired. Full refund recorded.</p>}</div>})}
 {!shown.length&&<div className="empty-state"><h3>No paid deliveries</h3><p>Paid orders will appear here automatically.</p></div>}<Pagination page={Math.min(page,Math.max(1,Math.ceil(filtered.length/perPage)))} setPage={setPage} total={filtered.length} perPage={perPage}/></div></>;
}
