export const categories = ['Electronics', 'Fashion', 'Home & Living', 'Phones', 'Computers', 'Beauty', 'Sports', 'Automotive'];

export const products = [
  { id: 1, name: 'Wireless Noise-Cancelling Headphones', category: 'Electronics', brand: 'SoundMax', vendor: 'Kigali Tech Store', price: 68000, oldPrice: 85000, rating: 4.8, reviews: 124, stock: 18, sku: 'MV-HDP-001', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80', description: 'Premium wireless headphones with active noise cancellation, deep bass and all-day battery life.', attributes: { Color: 'Black', Material: 'Aluminium', Weight: '250g' } },
  { id: 2, name: 'Smartphone Pro 5G 256GB', category: 'Phones', brand: 'Nova', vendor: 'Smart Hub Rwanda', price: 549000, oldPrice: 620000, rating: 4.6, reviews: 87, stock: 9, sku: 'MV-PHN-205', image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80', description: 'Fast 5G smartphone with a bright AMOLED display, pro camera system and 256GB storage.', attributes: { Color: 'Blue', Storage: '256GB', Model: 'N5 Pro' } },
  { id: 3, name: 'Minimalist Office Chair', category: 'Home & Living', brand: 'ComfortPro', vendor: 'HomeStyle Kigali', price: 185000, oldPrice: 220000, rating: 4.7, reviews: 53, stock: 24, sku: 'MV-CHR-102', image: 'https://images.unsplash.com/photo-1505843490701-5be4e7c0a8f7?auto=format&fit=crop&w=900&q=80', description: 'Ergonomic office chair designed for long working sessions with adjustable height and lumbar support.', attributes: { Color: 'Grey', Material: 'Mesh', Capacity: '120kg' } },
  { id: 4, name: 'Classic Leather Sneakers', category: 'Fashion', brand: 'UrbanStep', vendor: 'Urban Closet', price: 72000, oldPrice: 90000, rating: 4.5, reviews: 41, stock: 31, sku: 'MV-SHO-443', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80', description: 'Clean everyday sneakers with a comfortable sole and durable leather upper.', attributes: { Color: 'White', Size: '39-45', Material: 'Leather' } },
  { id: 5, name: 'Smart Watch Active', category: 'Electronics', brand: 'Pulse', vendor: 'Kigali Tech Store', price: 99000, oldPrice: 125000, rating: 4.4, reviews: 66, stock: 16, sku: 'MV-WAT-331', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80', description: 'Fitness-focused smartwatch with heart-rate tracking, notifications and multiple sports modes.', attributes: { Color: 'Silver', Battery: '7 days', Water: '5ATM' } },
  { id: 6, name: 'Portable Blender', category: 'Home & Living', brand: 'FreshMix', vendor: 'Kitchen World', price: 42000, oldPrice: 52000, rating: 4.3, reviews: 29, stock: 40, sku: 'MV-BLD-072', image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=900&q=80', description: 'USB rechargeable portable blender for smoothies and fresh drinks on the go.', attributes: { Color: 'Sky Blue', Capacity: '450ml', Power: '80W' } },
  { id: 7, name: 'Professional Camera Kit', category: 'Electronics', brand: 'Canonix', vendor: 'Photo Pro Rwanda', price: 920000, oldPrice: 1040000, rating: 4.9, reviews: 38, stock: 5, sku: 'MV-CAM-912', image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80', description: 'Professional camera kit for creators, events and commercial photography.', attributes: { Sensor: '24MP', Lens: '24-70mm', Video: '4K' } },
  { id: 8, name: 'Skincare Essentials Set', category: 'Beauty', brand: 'GlowLab', vendor: 'Glow Beauty', price: 56000, oldPrice: 70000, rating: 4.7, reviews: 72, stock: 22, sku: 'MV-BEA-551', image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80', description: 'Daily skincare set with cleanser, serum and moisturizer for a simple routine.', attributes: { Skin: 'All types', Pieces: '3', Size: 'Travel friendly' } }
];

export const vendors = [
  { id: 1, name: 'Kigali Tech Store', category: 'Electronics', products: 148, rating: 4.9 },
  { id: 2, name: 'Urban Closet', category: 'Fashion', products: 92, rating: 4.7 },
  { id: 3, name: 'HomeStyle Kigali', category: 'Home & Living', products: 67, rating: 4.8 },
  { id: 4, name: 'Glow Beauty', category: 'Beauty', products: 51, rating: 4.6 }
];
